---
# Tools using the Chemistry Development Kit
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: CDK jobs
collection: cdk
repository-url: https://github.com/InformaticsMatters/squonk2-cdk/data-manager/cdk.yaml
repository-tag: '1.0.0'

jobs:
  cdk-molecular-descriptors:
    name: CDK molecular properties
    description: >-
      Calculate molecular properties using CDK's molecular descriptors.
    version: '1.0.0'
    category: comp chem
    keywords:
    - cdk
    - properties
    doc-url: 'https://discourse.squonk.it/t/job-cdk-molecular-descriptors/126'
    image:
      name: informaticsmatters/squonk2-cdk
      tag: 'latest'
      project-directory: /data
      working-directory: /data
      fix-permissions: true
    # The container has no entrypoint so this is the command that is executed.
    # The CLASSPATH environment variable in the container is set.
    command: >-
      java squonk.jobs.cdk.DescriptorsExec
      --input '{{ inputFile }}'
      --output '{{ outputFile }}'
      {% if alogp %}--alogp{% endif %}
      {% if xlogp %}--xlogp{% endif %}
      {% if jplogp %}--jplogp{% endif %}
      {% if hba %}--hba{% endif %}
      {% if hbd %}--hbd{% endif %}
      {% if tpsa %}--tpsa{% endif %}
      {% if fcsp3 %}--fcsp3{% endif %}
      {% if rotb %}--rotb{% endif %}
      {% if rings %}--rings{% endif %}
      {% if wiener %}--wiener{% endif %}
    variables:
      order:
        options:
        - outputFile
        - alogp
        - xlogp
        - jplogp
        - hba
        - hbd
        - tpsa
        - fcsp3
        - rotb
        - rings
        - wiener
      inputs:
        type: object
        required:
        - inputFile
        properties:
          inputFile:
            title: Input molecules
            mime-types:
            - chemical/x-mdl-sdfile
            type: file
      outputs:
        type: object
        properties:
          results:
            title: Output molecules
            mime-types:
            - chemical/x-mdl-sdfile
            creates: '{{ outputFile }}'
            type: file
            annotation-properties:
              fields-descriptor:
                origin: squonk2-job
                description: CDK molecular properties
                fields:
                  ALogP_CDK:
                    type: number
                    description: >-
                      ALogP (Ghose-Crippen LogKow)
                    required: false
                    active: true
                  ALogP2_CDK:
                    type: number
                    description: >-
                      ALogP2 from CDK
                    required: false
                    active: true
                  AMR_CDK:
                    type: number
                    description: >-
                      ALogP (Ghose-Crippen molar refractivity)
                    required: false
                    active: true
                  XLogP_CDK:
                    type: number
                    description: >-
                      logP using the XLogP method
                    required: false
                    active: true
                  JPLogP_CDK:
                    type: number
                    description: >-
                      logP model from J. Plante from Lhasa Ltd.
                    required: false
                    active: true
                  HBA_CDK:
                    type: number
                    description: >-
                      Hydrogen bond acceptor count
                    required: false
                    active: true
                  HBD_CDK:
                    type: number
                    description: >-
                      Hydrogen bond donor count
                    required: false
                    active: true
                  TPSA_CDK:
                    type: number
                    description: >-
                      Topological polar surface area (P. Ertl)
                    required: false
                    active: true
                  FCSP3_CDK:
                    type: number
                    description: >-
                      Fraction sp3 hybridised carbon atoms
                    required: false
                    active: true
                  ROTB_CDK:
                    type: number
                    description: >-
                      Number or rotatable bonds
                    required: false
                    active: true
                  RING_COUNT_CDK:
                    type: number
                    description: >-
                      Number of rings
                    required: false
                    active: true
                  RING_COUNT_ARO_CDK:
                    type: number
                    description: >-
                      Number of aromatic rings
                    required: false
                    active: true
                  RING_SYS_CDK:
                    type: number
                    description: >-
                      Number of ring systems
                    required: false
                    active: true
                  RING_SYS_ARO_CDK:
                    type: number
                    description: >-
                      Number of aromatic ring systems
                    required: false
                    active: true
                  WienerPath_CDK:
                    type: number
                    description: >-
                      Wiener path
                    required: false
                    active: true
                  WienerPolarity_CDK:
                    type: number
                    description: >-
                      Wiener polarity
                    required: false
                    active: true
              service-execution:
                service_ref: 'https://discourse.squonk.it/t/job-cdk-molecular-descriptors/126'
              derived-from: inputFile
      options:
        type: object
        required:
        - outputFile
        - alogp
        - xlogp
        - jplogp
        - hba
        - hbd
        - tpsa
        - fcsp3
        - rotb
        - rings
        - wiener
        properties:
          outputFile:
            title: Output file (.sdf)
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
          alogp:
            title: Calculate ALogP and AMR
            type: boolean
            default: true
          xlogp:
            title: Calculate XLogP
            type: boolean
            default: true
          jplogp:
            title: Calculate JPLogP
            type: boolean
            default: true
          hba:
            title: Calculate H-bond acceptors
            type: boolean
            default: true
          hbd:
            title: Calculate H-bond donors
            type: boolean
            default: true
          tpsa:
            title: Calculate topological polar surface area
            type: boolean
            default: true
          fcsp3:
            title: Calculate fraction SP3 carbons
            type: boolean
            default: true
          rotb:
            title: Calculate rotatable bond count
            type: boolean
            default: true
          rings:
            title: Calculate ring counts
            type: boolean
            default: true
          wiener:
            title: Calculate Wiener numbers
            type: boolean
            default: true
    tests:
      simple-execution:
        inputs:
          inputFile: data/dhfr_3d.sdf
        options:
          outputFile: foo/cdk-predictions.sdf
          alogp: true
          xlogp: true
          jplogp: true
          hba: true
          hbd: true
          tpsa: true
          fcsp3: true
          rotb: true
          rings: true
          wiener: true
        checks:
          exitCode: 0
          outputs:
          - name: foo/cdk-predictions.sdf
            checks:
            - exists: true
